### PR TITLE
fix(sort-objects): handle destructured dependencies

### LINKED ISSUE #619: Bug: Missing dependency detection for nested destructuring defaults in sort-objects
### Describe the bug

The `sort-objects` rule misses dependencies when a default value uses an identifier declared deeper inside another destructuring branch. It treats the order as valid even though one property depends on another.

### Code example

```js
let {
  a = nested,
  b: { nested } = { nested: 'default' },
} = obj;
```

Expected: dependency error forcing b before a. Actual: passes with no error and no fix suggested.

### ESLint version

v9.39.1

### ESLint Plugin Perfectionist version

next

### Additional comments

_No response_

### Validations

- [x] Read the [docs](https://perfectionist.dev).
- [x] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

### PR DESCRIPTION
**Pull request by azat-io**
### Description

Fix `sort-objects` dependency detection to gather identifiers from nested destructuring patterns so default values can’t be reordered ahead of their declarations. Adds regression tests for nested defaults, rest elements, and array patterns to lock the behavior.

### Additional context

Close #619

---

### What is the purpose of this pull request? 

- [x] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [ ] Other

### Before submitting the PR, please make sure you do the following

- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves.
- [x] Ideally, include relevant tests that fail without this PR but pass with it.
- [x] Read [contribution guidelines](https://github.com/azat-io/eslint-plugin-perfectionist/blob/main/contributing.md).

### CODE REVIEW

File: rules/sort-objects.ts [hunk 1]
```diff
@@ -144,6 +144,63 @@ export default createEslintRule<Options, MessageId>({
...
+        pattern: DestructuringPattern,
+      ): string[] {
+        if (pattern.type === 'AssignmentPattern') {
+          return extractNamesFromPattern(pattern.left as DestructuringPattern)
+        }
+
+        if (pattern.type === 'ObjectPattern') {
+          let names: string[] = []
+          for (let property of pattern.properties) {
+            if (property.type === 'Property') {
```
Comment (hugop95) [inline rules/sort-objects.ts]: @azat-io 

[nit] A `switch-case` on `property.type` with `UnreachableCaseError` is safer and more readable IMO (there are 2 cases today).

```ts
function extractNamesFromPattern(pattern: TSESTree.Node): string[] {]
  switch (pattern.type) {

    [...]

    case TSESTree.AST_NODE_TYPES.ObjectPattern:
      return pattern.properties.flatMap(extractNamesFromObjectPatternProperty)
    
     [...]

  function extractNamesFromObjectPatternProperty(
    property: TSESTree.RestElement | TSESTree.Property,
  ): string[] {
    switch (property.type) {
      case TSESTree.AST_NODE_TYPES.RestElement:
        return extractNamesFromPattern(property.argument)
      case TSESTree.AST_NODE_TYPES.Property:
        return extractNamesFromPattern(property.value)
      default:
        throw new UnreachableCaseError(property)
    }
  }
```

File: rules/sort-objects.ts [hunk 2]
```diff
@@ -144,6 +144,63 @@ export default createEslintRule<Options, MessageId>({
         sourceCode,
       })
 
+      type DestructuringPattern =
+        | TSESTree.AssignmentPattern
+        | TSESTree.ObjectPattern
+        | TSESTree.ArrayPattern
+        | TSESTree.Identifier
+
+      function extractNamesFromPattern(
```
Comment (hugop95) [inline rules/sort-objects.ts]: @azat-io 

Could we put this function at the bottom ? We don't benefit from nesting it here, and it's harder to read IMO.

File: rules/sort-objects.ts [hunk 3]
```diff
@@ -144,6 +144,63 @@ export default createEslintRule<Options, MessageId>({
...
+        pattern: DestructuringPattern,
```
Comment (hugop95) [inline rules/sort-objects.ts]: @azat-io 

`DestructuringPattern` doesn't bring type safety here as we cast all usages to `as DestructuringPattern`.
Typing `pattern: TSESTree.Node` is more explicit here IMO.

File: rules/sort-objects.ts [hunk 4]
```diff
@@ -144,6 +144,63 @@ export default createEslintRule<Options, MessageId>({
...
+      ): string[] {
+        if (pattern.type === 'AssignmentPattern') {
```
Comment (hugop95) [inline rules/sort-objects.ts]: @azat-io 

I find `switch-casing` on `pattern.type` better. There are 4 cases:
- `AssignmentPattern`
- `ObjectPattern`
- `ArrayPattern`
- `Identifier` (the latest)
- `default` (unhandled).

File: rules/sort-objects.ts [hunk 5]
```diff
@@ -144,6 +144,63 @@ export default createEslintRule<Options, MessageId>({
...
+                ...extractNamesFromPattern(
+                  property.argument as DestructuringPattern,
+                ),
+              )
+            }
+          }
+          return names
+        }
+
+        if (pattern.type === 'ArrayPattern') {
```
Comment (hugop95) [inline rules/sort-objects.ts]: @azat-io 

Same thing here: I think that a `switch-case` and a dedicated function makes it easier to read:

```ts
function extractNamesFromPattern(pattern: TSESTree.Node): string[] {
  switch (pattern.type) {

   [...]

    case TSESTree.AST_NODE_TYPES.ArrayPattern:
      return pattern.elements.flatMap(extractNamesFromArrayPatternElement)

    [...]

  function extractNamesFromArrayPatternElement(
    element: TSESTree.DestructuringPattern | null,
  ): string[] {
    if (!element) {
      return []
    }
    switch (element.type) {
      case TSESTree.AST_NODE_TYPES.RestElement:
        return extractNamesFromPattern(element.argument)
      default:
        return extractNamesFromPattern(element)
    }
  }
```

File: rules/sort-objects.ts [hunk 6]
```diff
@@ -278,6 +335,16 @@ export default createEslintRule<Options, MessageId>({
             }
 
             let name = getNodeName({ sourceCode, property })
+            let dependencyNames = [name]
+            if (isDestructuredObject) {
+              let namesFromPattern = extractNamesFromPattern(
```
Comment (hugop95) [inline rules/sort-objects.ts]: @azat-io 

I think that we can simplify this to:

```ts
let dependencyNames = [name]
if (isDestructuredObject) {
  dependencyNames = [
    ...new Set(extractNamesFromPattern(property.value)),
  ]
}
```

We don't need to check if `namesFromPattern.length > 0`: in the previous version, we were overriding the original `dependencyName` if the object was destructured.

**Comment by azat-io** [comment]
@hugop95 Thanks for the comments. I've refactored it.
