### PR TITLE
fix: `sort-variable-declarations` #254 and #256: dependencies related issues

### LINKED ISSUE #254: Bug: `sort-variable-declarations`
### Describe the bug

```
error  'position' was used before it was defined  @typescript-eslint/no-use-before-define
```

when use

```json5
{
   '@typescript-eslint/no-use-before-define': 'error',
   'perfectionist/sort-variable-declarations': [
        'error',
        {
            ignoreCase: true,
            order: 'asc',
            type: 'alphabetical',
        },
    ]
}
```

### Code example

Before lint

```js
for (
    let position = editor.state.selection.$anchor,
        depth = position.depth;
    depth > 0;
    depth--
) {
// ... editor update state
}
```

After fix

```js
for (
    let depth = position.depth,
        position = editor.state.selection.$anchor;
    depth > 0;
    depth--
) {
// ... editor update state
}
```

### ESLint version

v8

### ESLint Plugin Perfectionist version

v4

### Additional comments

_No response_

### Validations

- [X] Read the [docs](https://perfectionist.dev).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

### LINKED ISSUE #256: Bug: `sort-variable-declarations`: Missing dependency detections
### Describe the bug

Issues related to https://github.com/azat-io/eslint-plugin-perfectionist/issues/254.

The following elements are not detected as dependencies and are considered invalid when they should not:

- [ ] Negation operator:
```
let b = 1,
    a = !b;
```

- [ ] Optional chained elements:
```
let b = {x: 1},
     a = b?.x;
```

- [ ] Non-null assertion operator:
```
let b = 1,
    a = b!;
```

- [ ] `as` expressions:
```
let b = 1,
    a = b as any;
```

- [ ] Type assertion expressions:
```
let b = 1,
    a = <any>b;
```

- [ ] All sorts of ternary expressions:
```
let b = 1,
    a = b ? 0 : 1;
```

- [ ] Template literal expressions:
```
let b = '',
    a = `${b}`
```

- [ ] Spread elements:
```
let b = {x: 1},
    a = {...b}
```

### Code example

See above

### ESLint version

8.57.0

### ESLint Plugin Perfectionist version

v3.4.0

### Additional comments

_No response_

### Validations

- [X] Read the [docs](https://perfectionist.dev).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

### PR DESCRIPTION
**Pull request by hugop95**
### Description

This PR fixes dependency related issues within the `sort-variable-declarations` rule.
It also adds a couple related additional unit tests in `sort-classes`.

Fixes #254.
Fixes #256.

### Chained elements:
```
let b = {x: 1},
     a = b.x;
```

- [x] Tests added.

### Negation operator (`!` ):
```
let b = 1,
    a = !b;
```
- [x] Tests added.

### Optional chained elements:
```
let b = {x: 1},
     a = b?.x;
```

- [x] Tests added.

### Non-null assertion operator (`!`):
```
let b = 1,
    a = b!;
```

- [x] Tests added.

### `as` expressions:
```
let b = 1,
    a = b as any;
```

- [x] Tests added.

### Type assertion expressions:
```
let b = 1,
    a = <any>b;
```

- [x] Tests added.

### All sorts of ternary expressions:
```
let b = 1,
    a = b ? 0 : 1;
```
- [x] Tests added.

### Template literal expressions:
```
let b = '',
    a = `${b}`
```

- [x] Tests added.

### Spread expressions:
```
let b = {x: 1},
    a = {...b}
```
- [x] Tests added.

### What is the purpose of this pull request?

- [x] Bug fix

### CODE REVIEW

File: rules/sort-variable-declarations.ts [hunk 1]
```diff
@@ -89,16 +89,44 @@ export default createEslintRule<Options, MESSAGE_ID>({
...
+            }
+
+            if (nodeValue.type === 'ConditionalExpression') {
+              traverseNode(nodeValue.test)
+              traverseNode(nodeValue.consequent)
+              traverseNode(nodeValue.alternate)
+            }
+
             if (
-              'body' in nodeValue &&
```
Comment (hugop95) [inline rules/sort-variable-declarations.ts:97]: This condition was removed because function expressions bodies are not required to have their dependencies before them:

```ts
let a = () => { return b},
     b = 1
```
is correct in Typescript.
