### PR TITLE
fix: `partitionByComment` doesn't Respect Comment Boundaries in `sort-union-types`

### LINKED ISSUE #306: Bug:  `partitionByComment` Doesn't Respect Comment Boundaries in `sort-union-types`
### Describe the bug

When using the `partitionByComment: true` option in `sort-union-types`, the union type members are expected to be sorted within groups that are separated by comments. However, the current behavior ignores comment boundaries and sorts the entire union type globally, even across different comment sections.

### Code example

Given this input:

```tsx
type T =
  // Group 1
  | Z
  | B
  // Group 2
  | C
  | A;
```

Expected output (sorting within comment partitions):

```
type T =
  // Group 1
  | B
  | Z
  // Group 2
  | A
  | C;
```

Actual output (comments ignored, globally sorted):

```
type T =
  // Group 1
  | A
  | B
  // Group 2
  | C
  | Z;
```

### ESLint version

8.57.0

### ESLint Plugin Perfectionist version

3.8.0

### Additional comments

`partitionByComment` works in others, for example `sort-exports`

### Validations

- [X] Read the [docs](https://perfectionist.dev).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

### PR DESCRIPTION
**Pull request by hugop95**
Resolves #306 ... But not completely.

Also applies to `sort-intersection-types`

## The problem

```ts
type T =
  // Group 1
  | Z
  | B
  // Group 2
  | C
  | A;
```
`// Group 1` and `// Group 2` are not detected as partition comments

### Why

Partition comments are comments detected `directly` before a node: here: `Z` and `C`.
However, `|` is a token, so partition comments are not considered comments of `Z` and `C`.

### "True" fix

Write code as follows:

```ts
type T =
  // Group 1
  Z |
  B |
  // Group 2
  C |
  A;
```

However, some tools will make automatically format this as what we had in the first place.

## Proposed solution in this PR

When detecting comments for a given node:
- If the node has comments immediately before, OK, behavior as usual.
- If the node has a `|` token (`&` for `sort-interesection-types`), get comments before that token rather than the node.

## The problems with this solution

Unfortunately, doing this has consequences on other comments-related features (only if writing `|` before the node):
Comments associated to a node will not be moved around. This means that

```ts
type T =
  // Not a partition comment, follow Z!
  | Z
  | B
```
gets autofixed to
```ts
type T =
// Not a partition comment, follow Z!
| B  
| Z
```

The reason is that nodes being re-ordered do **not** include the `|` token with them (and as such, comments above that token).

Is it possible to make a fix to include those tokens and their comments in the sorting algorithm? Sure, but in my opinion, it's not worth the potential things that can break (especially if mixing both writing styles in the same union/intersection types).

## What is the purpose of this pull request?

- [x] Bug fix

### CODE REVIEW

**Comment by hugop95** [comment]
@azat-io For info!

**Comment by hugop95** [comment]
I realize this is not a full fix, but that's the simplest thing I can think of at the moment.

File: rules/sort-intersection-types.ts [hunk 1]
```diff
@@ -261,7 +261,7 @@ export default createEslintRule<Options, MESSAGE_ID>({
             (partitionComment &&
               hasPartitionComment(
                 partitionComment,
-                getCommentsBefore(type, sourceCode),
+                getCommentsBefore(type, sourceCode, '&'),
```
Comment (azat-io) [inline rules/sort-intersection-types.ts:264]: I think it looks like a hack. It might be worth refactoring in the future.

**Review by azat-io — APPROVED** [review]
