### PR TITLE
fix(all-rules): Ignores whitespaces in node names

### LINKED ISSUE #181: Bug: [`perfectionist/sort-intersection-types`] indentation can impact rule interpretation
### Describe the bug

In the screenvideo below, you can see 2 strange behaviours:
- the rule works but is broken when changing the indentation
- when inverting 2 types as requested by the error message, a new error message is raised and contradicts the previous one

### Code example

Project (for testing – remove the `eslint-disable` comment): https://github.com/OlivierZal/melcloud-api/blob/fd854ab272e3b818b0570878d9815e938481d7ec/src/facades/interfaces.ts#L61

```
setHolidayMode: (({
    enabled,
    from,
    days,
  }: {
    enabled?: true
    from?: string
    days: number
  }) => Promise<FailureData | SuccessData>) &
    (({
      enabled,
      from,
      to,
    }: {
      enabled?: true
      from?: string
      to: string
    }) => Promise<FailureData | SuccessData>) &
    (({ enabled }: { enabled: false }) => Promise<FailureData | SuccessData>)
```

### ESLint version

v9.7.0

### ESLint Plugin Perfectionist version

v3.0.0

### Additional comments

Here is a screenvideo:

https://github.com/user-attachments/assets/b8c1cb15-589a-493e-a52f-2f846e006b1f

### Validations

- [X] Read the [docs](https://perfectionist.dev).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

### PR DESCRIPTION
**Pull request by hugop95**
Resolves #181 .

### Description

Today with the `alphabetical` or `natural` sort, the following code is valid

```ts
type T =
{ a: string } &
{ b: string }
```

but this one is not:

```ts
type T =
{ a: string } &
{  b: string }
```

The issue lies in the fact that `{  b` is "lower" than `{ a` because of the whitespace before `b`.
Giving the possibility for users to ignore whitespaces can solve this issue.  

### Changes

This PR changes the following:
- [x] All whitespace-like characters (including `\n`) will be ignored in node names.
- [x] Add tests. Refactored `compare` file to reach 100% code coverage.

### What is the purpose of this pull request?

- [x] New Feature

### CODE REVIEW

**Comment by azat-io** [comment]
Are you sure this should be a separate option and not the default behavior?

**Comment by hugop95** [comment]
@azat-io I am trying to find cases where a user would **not** want to ignore whitespaces. It's possible that there are none, in which case this is better to have this as a default option indeed. @OlivierZal, what do you think?

**Comment by OlivierZal** [comment]
I would say it rather should be the default behavior since IMO `perfectionist` should not care about indentation, which belongs to `stylistics` concerns.

**Comment by hugop95** [comment]
> I would say it rather should be the default behavior since IMO `perfectionist` should not care about indentation, which belongs to `stylistics` concerns.

This is unfortunately more than just a stylistic concern: all whitespace are removed, meaning that for

```ts
type T = 
  'I am a string' |
  'I am a         string'
```
the two members of the type are now the same.

I know that my example is not really representative of an issue someone would have in practice, but I'm wondering if we are not potentially impacting something else.

**Comment by OlivierZal** [comment]
Oh I see, so the question is: are there cases where someone wants spaces to be taken into account, and what's the most widly used and accepted practice in the dev community in order to decide which is the default.

**Comment by hugop95** [comment]
@OlivierZal Pretty much. On one end, I think that "stylistic" related issues like

```ts
type T =
{ a: string } &
{  b: string }
```

can be fixed by prettifying tools like `prettier`. On the other, if these tools are not used, this affects sorting rules.

**Comment by OlivierZal** [comment]
My problem is precisely that I use prettier: even if I keep a working  indentation, prettier will change it.

**Comment by OlivierZal** [comment]
Based on our conversation, I would vote for defaulting the behavior to ignore white spaces.

File: utils/compare.ts [hunk 1]
```diff
@@ -38,10 +38,18 @@ export let compare = (
...
+  let formatString: (value: string) => string
+  if (options.type === 'line-length') {
+    formatString = (string: string) => string
+  } else {
+    formatString = (value: string) => {
+      let valueToCompare = value
+      if (options.ignoreCase) {
+        valueToCompare = valueToCompare.toLowerCase()
+      }
+      return valueToCompare.replaceAll(/\s/g, '')
```
Comment (OlivierZal) [inline utils/compare.ts:50]:
```ts
return valueToCompare.replaceAll(/\s/g, '')
```

or just

```ts
return valueToCompare.trim()
```

?

Comment (hugop95) [reply utils/compare.ts:50]: Trimming would be the ideal! 

Unfortunately, it doesn't solve your case: `'{  b: string }'.trim()` is still `'{  b: string }'`

Comment (OlivierZal) [reply utils/compare.ts:50]: oh, right...

**Comment by azat-io** [comment]
Awesome fix, thank you!
